mozilla/irlpodcast

_posts/2017-08-21-episode-5-i-spy-with-my-digital-eye.md
Updates the publish time of episode 5 to trigger a build.
1. merge this PR
2. check staging site: https://stage.irlpodcast.org/
3. episode 5 should be present on home page with functioning player
4. click episode 5 title to go to episode 5 landing page - everything should look/function correct
You can compare against the episode 5 having, up-to-date [dev site](https://mozilla.github.io/irlpodcast/) if needed.
1. push the `master` branch to the `prod` branch, e.g. `git push origin master:prod`
=> Launch episode 5.

_sass/irlpodcast.scss, ringtones.md
Please weigh in if you think any of the gifs used are inappropriate. Or if you have any sweet gifs to add.
=> Add easter egg to ringtones page & fix artwork alignment on home page.

_includes/episode-module.html, _posts/2017-05-25-episode-0-trailer.md, _posts/2017-06-26-episode-1-all-your-data.md, _posts/2017-07-10-episode-2-the-neutral-zone.md, _posts/2017-07-24-episode-3-hack-jobs.md, _posts/2017-08-07-episode-4-the-care-and-feeding-of-your-troll.md, _posts/2017-08-21-episode-5-i-spy-with-my-digital-eye.md, _posts/2017-09-04-episode-6-all-access-pass.md, _posts/2017-09-18-episode-7-free-speech-limited.md, _posts/2017-11-15-bonus-1-status-update.md, _posts/2017-12-11-bonus-2-net-neutrality-emergency.md, _posts/2018-01-08-episode-8-bot-or-not.md, _posts/2018-01-22-episode-9-digital-overload.md, _posts/2018-02-05-episode-10-face-value.md, _posts/2018-02-16-episode-11-cloak-of-invisibility.md, _posts/2018-03-05-episode-12-algorisky.md, _sass/irlpodcast.scss
Demo:
http://sandbox.equalparts.io/irlpodcast/
=> Implement new simplecast player.

_posts/2018-04-03-episode-14-ctrl-alt-facts.md, ringtones.md
Makes sure the script loads on the dev server.
=> Updates path to kirl JS script to use relative_url

.gitignore, bin/build.sh, bin/push-gh-pages.sh
Check the comments in `push-gh-pages.sh` for accuracy?
=> Update Hugo build directory and comment push-gh-pages.sh.

config-dev.toml, config-prod.toml, config-stage.toml
=> Fix typos in .toml config files.

layouts/_default/baseof.html, layouts/partials/episode-module.html, src/js/main.js, src/js/mozilla.lazy-load.js, src/scss/irlpodcast.scss
- Update local dev Docker to use latest Hugo
=> [fix #7] Lazy-load simplecast players.

bin/build.sh, docker-compose.yml, gulpfile.js, package.json
- Make filesystem mount in docker-compose.yml delegated
- Only hash CSS/JS file names when building for dev/stage/prod
=> [fix #85] Improve local Docker dev.

content/episodes/2018-07-16-S03E02-press-play.md
The episode was accidentally merged while backdated for dev.
=> Fix S03E02 publish date

README.md, archetypes/episodes.md
When creating an episode using the archetype, pre-populate as much as possible from information already provided in the file name.
=> Get season, episode, and title from file name

archetypes/episodes.md
Group similar properties in the episode archetype. This should make it
easier to catch errors and inappropriate differences.
=> Reorder episode archetype

layouts/episodes/single.html, src/scss/irlpodcast.scss
=> Add links to next and previous episodes

content/episodes/2018-09-10-S03E06-kids-these-days.md
Slight edit to show notes with an updated blog URL.
=> Update S03E06 show notes

content/about.md, layouts/_default/baseof.html, layouts/partials/footer.html, layouts/partials/header.html, src/scss/components/_footer.scss, src/scss/components/_header.scss, src/scss/includes/_mixins.scss, src/scss/irlpodcast.scss
Close mozilla/irlpodcast#124
Fix Bug #1469401
- Made footer into header
- Added site footer
- Removed privacy and cookies links from about page
- Added privacy and cookies links to footer
=> Add footer with CC license

README.md
Update README with more detail around communication for doing a deployment.
=> Update README with deploy info

archetypes/episodes.md, content/episodes/2017-05-25-S01E00-trailer.md, content/episodes/2017-06-26-S01E01-all-your-data.md, content/episodes/2017-07-10-S01E02-the-neutral-zone.md, content/episodes/2017-07-24-S01E03-hack-jobs.md, content/episodes/2017-08-07-S01E04-the-care-and-feeding-of-your-troll.md, content/episodes/2017-08-21-S01E05-i-spy-with-my-digital-eye.md, content/episodes/2017-09-04-S01E06-all-access-pass.md, content/episodes/2017-09-18-S01E07-free-speech-limited.md, content/episodes/2017-11-15-S01B01-status-update.md, content/episodes/2017-12-11-S01B02-net-neutrality-emergency.md, content/episodes/2018-01-08-S02E01-bot-or-not.md, content/episodes/2018-01-22-S02E02-digital-overload.md, content/episodes/2018-02-05-S02E03-face-value.md, content/episodes/2018-02-16-S02E04-cloak-of-invisibility.md, content/episodes/2018-03-05-S02E05-algorisky.md, content/episodes/2018-03-19-S02E06-social-bubble-bath.md, content/episodes/2018-04-03-S02E07-ctrl-alt-facts.md, content/episodes/2018-06-18-S03E00-introducing-season-3.md, content/episodes/2018-07-02-S03E01-the-grand-bargain.md, content/episodes/2018-07-16-S03E02-press-play.md, content/episodes/2018-07-30-S03E03-paid-attention.md, content/episodes/2018-08-13-S03E04-virtual-connections.md, content/episodes/2018-08-27-S03E05-bullying-and-bonding-online.md, content/episodes/2018-09-10-S03E06-kids-these-days.md, content/episodes/2018-10-04-S03E07-what-to-expect-when-youre-electing.md, layouts/partials/episode-module.html
This PR adds the host's twitter handle to each episode and archetype.
Then it consumes the strings when making the Twitter share text.
Closes #140
=> Add host to episodes, archetype, and share string.

content/episodes/2018-12-10-S04E02-your-password-is-the-worst.md
Based on the [request doc](https://docs.google.com/document/d/1ohl2g5GYrcyOD4XDuj4EA4IK5AwHv_QTiQfVO5jTYmQ/edit).
=> Update transcript for S4E02.

src/scss/base/elements/_links.scss, src/scss/includes/_mixins.scss, src/scss/includes/_variables.scss, src/scss/irlpodcast.scss
mozilla/irlpodcast#128
Add hover, focus and active styles.
Consolidate default link declaration to single file.
=> Add :hover :focus and :active styles

layouts/404.html, layouts/index.html, layouts/partials/episode-module.html, layouts/partials/newsletter.html
Some accessibility regressions have crept in over time as things have been moved around and reused.
- add alt text
- add iframe title
- remove duplicate ids
=> Accessibility tweaks

layouts/partials/footer.html, src/scss/components/_footer.scss
=> Add ringtones link to footer #81

src/js/episode14.js
=> Fix episode 14 easter egg (#162)

bin/build.sh
Prevent jenkins errors like the following: https://ci.us-west.moz.works/blue/rest/organizations/jenkins/pipelines/irlpodcast/branches/dev/runs/55/nodes/6/steps/7/log/?start=0
=> Fix filesystem permissions after build

content/seasons/season4.md
Fixes #180
I don't think this URL is linked from anywhere, but it seems nice to have.
=> Add /season4/ listing URL (Fixes #180)

layouts/partials/episode-module.html
Added it to the images on the homepage a while ago, not sure how I missed the episode pages.
=> Add alt text to episode page cover art

bin/slack-notify.sh
https://github.com/mozmeao/infra/issues/1043
=> update jenkins to use vpn

gulpfile.js, package-lock.json, package.json, src/js/mozilla.cookies.js
- Updates Gulp to v4.0.0 and also:
- gulp-eslint v5.0.0
- gulp-minify v3.1.0
- gulp-sass v4.0.2
- gulp-stylelint v8.0.0
- stylelint v9.10.1
- yargs v13.2.1
Running locally this seems to be working as expected, but some review from folks more familiar to the code would be good.
=> Update Gulp to v4.0.0 (Fixes #183)

content/episodes/2023-09-26-S07E00-introducing-season-7.md
=> Updated S07E00 title

layouts/partials/header.html
to: https://donor.mozilla.org/page/FUNWKPJMPBA?form=irl-podcast
=> Updated Donate Button URL
